language: node_js

node_js:
  - lts/*

sudo: required

install:
  - yarn

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: blog/.vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master

notifications:
  email: 
    recipients:
      - 1907004005@qq.com
    on_success: change
    on_failure: always
